### PR TITLE
Update README for consistent semicolon usage

### PR DESCRIPTION
**Pull request by djds23**
The current README is perfectly fine, however the lack of consistency was distracting.

### CODE REVIEW

**Comment by maxbeatty** [comment]
We use [Standard Style](http://standardjs.com) which does not use semicolons

**Comment by jcblw** [comment]
@djds23 if you like, make a PR removing the semicolons, and that I more likely to be accepted.

**Comment by maxbeatty** [comment]
What would be super awesome is to lint the JS code blocks in Markdown documents to keep everything consistent

**Comment by jcblw** [comment]
Yeah i have not seen that before, I sure its out there tho.

**Comment by maxbeatty** [comment]
😉 https://github.com/hapijs/lab/pull/513

**Pull request closed without merging**
