### PR TITLE
First PR

### PR DESCRIPTION
**Pull request by yTakkar**
Introduced `ES6` syntax to JS files.
And some minor changes in installation command and other projects' list of `README.md`.

### CODE REVIEW

**Comment by zenflow** [comment]
This module currently supports node version 4, which does not support ES6 syntax (without the `--harmony` flag) so I think this can't be merged *right now*.

But node version 4 reaches End-Of-Life on 2018-04-30. So maybe then we can stop supporting node version 4 too, and switch to ES6 syntax.

**Comment by zenflow** [comment]
@yTakkar I suggest breaking up this PR into separate PRs

**Comment by yTakkar** [comment]
@zenflow I think you're right, I should break up this PR into separate PRs

**Comment by zenflow** [comment]
@yTakkar Maybe open 3 fresh PRs rather than undoing changes here, so it's easier to review

**Comment by maxbeatty** [comment]
👋 thanks for contributing! We've found more success in the past when someone creates an issue with a suggestion for a change; a majority of people agree on it, and then a Pull Request is created.

**Comment by zenflow** [comment]
@maxbeatty Yeah, that approach is usually better, but for simple changes like f1cd386a5bc42e26433d9f5867756ddbeded3a94 it's easier and faster and makes more sense to suggest the change and discuss it in a PR, right?

**Comment by zenflow** [comment]
I think the reason it's better to discuss non-trivial changes in an issue first is because it could be rejected and then your time coding the changes was wasted.

**Comment by yTakkar** [comment]
But what if someone suggests any change and there's no issue about that change??

**Comment by yTakkar** [comment]
I'll suggest merging it, after all it's a transition of code to es6 onyl!!

**Comment by maxbeatty** [comment]
To minimize wasted effort, make sure your change is wanted before spending time on it. Issues are a good way to do that. Well-written Pull Request descriptions are another way. 

Today, I do not see enough benefit to accept these changes. If in the future new syntax results in a performance gain, safer execution, or similar improvement, I would be open to updating it.

**Comment by zenflow** [comment]
> I mean PRs will never be accepted/merged if it doesn't have any related issue??

I think there are exceptions. See my comment https://github.com/motdotla/dotenv/pull/281#issuecomment-370867249. I don't know if @maxbeatty agrees because he didn't reply to me.

**Pull request closed without merging**
