### PR TITLE
Add support for backticks

### PR DESCRIPTION
**Pull request by motdotla**

### CODE REVIEW

**Comment by s100** [comment]
Was it necessary to bump the major version number for this? Normally, adding a new feature isn't a breaking change.

**Comment by T0biii** [comment]
@s100 i think it is a breaking change see also: "If you had values containing the backtick character, please quote those values with either single or double quotes."
https://github.com/motdotla/dotenv/blob/master/CHANGELOG.md

**Comment by motdotla** [comment]
@s100 it is a good point you raise. The difficulty with the nature of this repo (and we err on the side of safety) is that a regex change on the parser can break edge cases for users of the older version. 

For example, in this case there could be users out there with a value like this:

`` KEY=ab`cd ``

**Comment by mo** [comment]
@motdotla what are the security implications of backtick support?

**Comment by motdotla** [comment]
@mo great question, Mo. Also great short handle!

There is no execution of variables (as there is in node template variables), so there are no additional security implications here.

The backticks simply act as a parsing wrapper - like single or double quotes.

**Pull request merged**
