### PR TITLE
feat: drop Node 10 support

### LINKED ISSUE #557: Drop Node 10 support
Because it's [EOL](https://nodejs.org/en/about/releases).

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
BREAKING CHANGE: Node@>=12 is required

---

Closes #557

### CODE REVIEW

**Review by pan93412 — APPROVED** [review]
LGTM. But would we use the features that Node 10 didn't bring to us?

**Comment by jimmywarting** [comment]
> LGTM. But would we use the features that Node 10 didn't bring to us?

how about switching to esm instead?

**Comment by UltiRequiem** [comment]
> > LGTM. But would we use the features that Node 10 didn't bring to us?
> 
> how about switching to esm instead?

This would be the best

**Review by jimmywarting — APPROVED** [review]

**Review by UltiRequiem — APPROVED** [review]

**Comment by motdotla** [comment]
Thank you for this @MichaelDeBoey

**Comment by motdotla** [comment]
> > > LGTM. But would we use the features that Node 10 didn't bring to us?
> > 
> > 
> > how about switching to esm instead?
> 
> This would be the best

Considering this. 

Would anyone like to chime in on potential downsides?

**Comment by Fotiman** [comment]
> > > > LGTM. But would we use the features that Node 10 didn't bring to us?
> > > 
> > > 
> > > how about switching to esm instead?
> > 
> > 
> > This would be the best
> 
> Considering this.
> 
> Would anyone like to chime in on potential downsides?

Downside: there are probably many existing applications that still rely on commonjs, and therefore would no longer be able to upgrade this package if it switches to esm.

**Comment by motdotla** [comment]
Yes, we have considered ESM. We will move to it at sometime but this is a very heavily relied on library and as a result we are going to maintain the status quo at this time.

**Pull request merged**
