### PR TITLE
Allow for `import "dotenv/config";` in Node.js

### PR DESCRIPTION
**Pull request by franciscop**
Currently the officially recommended method for auto-importing works with Babel-like configuration that automatically resolves `dotenv/config` to `dotenv/config.js`. However, Node.js doesn't do this resolution, and instead you have to manually specify the extension like this:

```js
// Babel OK, doesn't work on Node.js
import "dotenv/config";

// Works on Node.js (and Babel etc)
// See https://github.com/motdotla/dotenv/issues/89#issuecomment-587753552
import "dotenv/config.js";
```

A way of fixing this is by defining the export mapping in `package.json` as [explained in Node.js documentation](https://nodejs.org/api/packages.html#packages_package_entry_points):

```js
  "exports": {
    ".": "./lib/main.js",
    "./config": "./config.js"
  },
```

### CODE REVIEW

**Comment by RA80533** [comment]
This is a much-needed feature for those of us using more recent releases of Node.js.

@franciscop Are the failing tests related to the change made in package.json?

**Comment by franciscop** [comment]
@RA80533 It seems the current `master` is failing for me locally as well. I just hopefully fixed the tests :)

**Comment by motdotla** [comment]
thank you for this

**Comment by franciscop** [comment]
Thanks for accepting it!

**Pull request merged**
