### PR TITLE
fix: dotenv/config typings

### PR DESCRIPTION
**Pull request by max-hk**
This pull request fix typings error thrown by TypeScript when we load `dotenv/config` with dynamic import.

Without this PR, TypeScript will raise an error and fail to compile the following code.

```
await import('dotenv/config');

export {}
```

```
index.ts:1:14 - error TS7016: Could not find a declaration file for module 'dotenv/config'. '/path/to/project/node_modules/dotenv/config.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/dotenv` if it exists or add a new declaration (.d.ts) file containing `declare module 'dotenv/config';`
```

### CODE REVIEW

**Comment by danny-abc** [comment]
@motdotla can you take a look on this?

**Comment by motdotla** [comment]
Yes, will do so this weekend. Thank you for this.

**Comment by motdotla** [comment]
@max-hk can you elaborate on using `import('dotenv/config')` in typescript rather than..

```js
import dotenv from "dotenv"
dotenv.config()

console.log(process.env)
```

config.js is mainly to be used for preloading.

**Comment by motdotla** [comment]
Added to v13.0.0 release: https://github.com/motdotla/dotenv/blob/master/CHANGELOG.md#1300-2022-01-16

**Pull request merged**
