### PR TITLE
Add config option to override existing process.env values.

### PR DESCRIPTION
**Pull request by echernyavskiy**

### CODE REVIEW

**Review by gabriel-kohen-by — COMMENTED** [review]
@echernyavskiy  looks good overall. You might want to add the new capability to the README.md

**Comment by echernyavskiy** [comment]
> @echernyavskiy looks good overall. You might want to add the new capability to the README.md

@gabriel-kohen-by, done.

**Review by gabriel-kohen-by — APPROVED** [review]
LGTM

**Review by gabriel-kohen-by — CHANGES_REQUESTED** [review]
The build check seems to be failing

**Comment by motdotla** [comment]
thank you for the code here @echernyavskiy. we might soon re-open this and fork off it with final changes. we are going to add this feature soon for sure.

moving this conversation here: https://github.com/motdotla/dotenv/issues/436

**Pull request closed without merging**
