### PR TITLE
add 0.10 for LTS, drop iojs in favor of v4

### PR DESCRIPTION
**Pull request by maxbeatty**
some pretty big changes came to standard [between v5.0.0 and v5.0.1](https://github.com/feross/standard/compare/v5.0.0...v5.0.1) which makes installing it error using node v0.10. See [this travis job](https://travis-ci.org/motdotla/dotenv/jobs/80773606) for details. My local errors similarly:

```
~/Sites/dotenv on sm-dependencies
$ npm i standard@5.0.1
npm ERR! not a package /var/folders/v6/249xbd5x3rx3_q889fyf2bth0000gn/T/npm-13628-3QfkgRWs/github.com/eslint/eslint.git
npm ERR! Error: ENOENT, open '/var/folders/v6/249xbd5x3rx3_q889fyf2bth0000gn/T/npm-13628-3QfkgRWs/github.com/eslint/eslint.git-unpack/package.json'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 14.5.0
npm ERR! command "/Users/max/.nvm/v0.10.40/bin/node" "/Users/max/.nvm/v0.10.40/bin/npm" "i" "standard@5.0.1"
npm ERR! cwd /Users/max/Sites/dotenv
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm ERR! path /var/folders/v6/249xbd5x3rx3_q889fyf2bth0000gn/T/npm-13628-3QfkgRWs/github.com/eslint/eslint.git-unpack/package.json
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! not ok code 0
```

Going to open an issue to ask for guidance

### CODE REVIEW

**Comment by maxbeatty** [comment]
Opened https://github.com/feross/standard/issues/261 to see what our options may be

**Comment by maxbeatty** [comment]
The underlying issue has been resolved.

Should we go with all exact versions to hopefully prevent this sort of problem in the future? (this PR)
Should we switch to `.eslintrc` for a smaller dependency tree? (#95)

**Comment by motdotla** [comment]
@maxbeatty actually I am very up for that. I will remove the carets in package.json for exact versions.

**Comment by jcblw** [comment]
:+1: nice!

**Comment by motdotla** [comment]
These changes happened here: https://github.com/motdotla/dotenv/pull/93

**Pull request closed without merging**
