### PR TITLE
standard

### PR DESCRIPTION
**Pull request by feross**
We use this package in our test suite as a sanity check and the rules have changed a bit. :+1:

### CODE REVIEW

**Comment by jcblw** [comment]
:+1: sweet thanks man!

**Comment by maxbeatty** [comment]
why wasn't travis failing before this change?

**Comment by feross** [comment]
Because I just published the new version a few minutes ago and you hadn't re-run the tests :)

**Comment by maxbeatty** [comment]
thanks for being proactive but this could be avoided by following semver

**Comment by feross** [comment]
I'm a huge semver proponent, but it's not that simple. For a linter, any change, even in dependencies, is likely to break someone's code.

For example, eslint publishes patch versions when they improve a rule to detect some case that was being missed before. Makes sense to be a patch, since it's a bugfix: the rule wasn't working correctly before. But to end users, that patch version could cause eslint to start failing on code that passed before. This isn't theoretical. This happens all the time.

So, to be safe, literally every time we bump a dep, we would need to publish a major version. This isn't realistic or even useful. Regarding this PR, it was always the case that you should have spaces before/after keywords - it just wasn't catching this case.

**Pull request merged**
