### PR TITLE
add TypeScript types

### LINKED ISSUE #343: [feat-req] Support for TypeScript Declaration File
### Summary 

Hi there, 

Just started using dotenv, and loving its elegant simplicity.

Was trying it out on a TypeScript-based project and noticed that the latest dotenv version is out of sync with the available @types declaration. 

dotenv currently on v6.1.0
@types/dotenv currently supports dotenv 4.0

Wondering if it is ok to raise a feature request here in the dotenv project to include support for TypeScript Declaration Files?

### Background and Context

- http://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html
- https://www.npmjs.com/~types
- https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/dotenv

### PR DESCRIPTION
**Pull request by maxbeatty**
closes #343 

- [x] adds TypeScript declaration file to be bundled w/ npm module
- [x] use same type names for Flow and TypeScript
- [x] run flow and dtslint checks after tests on CI (will run slower but oh well)

### CODE REVIEW

**Comment by maxbeatty** [comment]
@miller-productions does this look like what you need for #343?

**Comment by miller-productions** [comment]
Hi @maxbeatty,

Thanks for having a go at this request, that is good of you.

I've just cloned your branch and had a basic look at it. A few issues popped up.

### Scenario

- Import maxbeatty's ts-types branch into a clean empty node/typescript project from scratch.
- Attempt to run the typescript compiler

### Expected
- The project compiles correctly

### Actual
```
error TS2688: Cannot find type definition file for 'node'.
error TS2580: Cannot find name 'Buffer'. Doyou need to install type definitions for node? Try `npm i @types/node
error TS1192: Module '"<your-path>/dotenv/types/index"' hasno default export.
```

### Steps to Demonstrate

1. ```git clone https://github.com/motdotla/dotenv.git && cd dotenv/```
2. ```git checkout ts-types ```
3. In a new directory, say for example adjacent to dotenv, start a new project from scrach
```
mkdir test-dotenv-typedef && cd test-dotenv-typedef
npm init --yes
npm install --save-dev typescript
touch server.ts
```
4. Edit server.ts
``` 
import dotenv from '../dotenv';
```
5. back in your shell...
```
npx tsc server.ts
```

**Comment by maxbeatty** [comment]
after doing some more reading, it looks like the way to resolve the "Cannot find type definition file for 'node'" error is to declare `@types/node` as a dependency of dotenv. since that would be the module's _only_ dependency, I think it's a better path forward to continue maintaining types in `@types/dotenv` so that anyone wanting types can cleanly opt in while anyone who doesn't installs only what they need

```
npm install dotenv 
npm install --save-dev @types/dotenv
```

I ported over my changes to https://github.com/DefinitelyTyped/DefinitelyTyped/pull/30217 so you can follow the progress there

**Comment by miller-productions** [comment]
Understood, thanks Max

**Pull request merged**
