### PR TITLE
suppress error messages by default

### PR DESCRIPTION
**Pull request by maxbeatty**
logging errors by default is scaring more people than it's helping. see #135 and [this travis output](https://travis-ci.org/jsperf/jsperf.com/builds/168675049#L1189) as examples

this should result in a major release

### CODE REVIEW

**Comment by maxbeatty** [comment]
@motdotla @jcblw do you agree logging the errors is doing more harm than good?

**Comment by jcblw** [comment]
I agree that this should be turned off by default.

**Comment by heitortsergent** [comment]
@maxbeatty are there any reasons to drop support for older versions of Node?

**Comment by maxbeatty** [comment]
Nothing significant is changing about the implementation that would prevent it from working, but those older versions are no longer receiving updates like security patches so I think it's better for the community at large to go forward. If you're using a sane semver range, you won't notice this.

**Comment by heitortsergent** [comment]
Based on the table [here](https://github.com/nodejs/LTS#lts-schedule), I would suggest leaving 0.12 support and opening a separate issue/PR for dropping support for it in Dec/Jan. That seems to be the timeline for ending critical patches to it.

**Comment by jcblw** [comment]
@maxbeatty  @motdotla  we looking to do a major bump with this? If so and you guys think #158 is cool we should probably get that in the bump as well.

**Comment by maxbeatty** [comment]
yes, should be a major version release because of the breaking change to the silent option

**Pull request merged**
