### PR TITLE
feat: support to parse home directory

### PR DESCRIPTION
**Pull request by brelian**
## Why we need this PR
This PR is committed to supporting parsing an env path with a home directory prefix since we haven't implemented it yet.

Snipaste_2021-05-06_20-02-45

## Related Issues
- #527

### CODE REVIEW

**Comment by motdotla** [comment]
This is cool @brelian. Can you tell me a little more about your use case?

For example, instead of using `~` why not do this in your config path:

```
require('dotenv').config({ path: path.join(os.homedir(), '/.env') })
```

**Comment by brelian** [comment]
> This is cool @brelian. Can you tell me a little more about your use case?
> 
> For example, instead of using `~` why not do this in your config path:
> 
> ```
> require('dotenv').config({ path: path.join(os.homedir(), '/.env') })
> ```

Hi @motdotla, thanks for your detailed comment in which case is a good solution. However, sometimes, I make an environment my env path, e.g.
```js
DOTENV_CONFIG_PATH=~/.env node -r dotenv/config my_script.js
``` 

Especially, I need to load those environment variables that locate in the home directory before starting my app since I don't want to put the env file along with my repo. In this way, I could prevent clean it up carelessly.

Thanks,
Pylon

**Comment by motdotla** [comment]
Makes sense. That is a good use case.

What OS are you running on? I run `DOTENV_CONFIG_PATH=~/.env node -r dotenv/config my_script.js` on a mac machine and it finds the `.env` successfully.

**Comment by brelian** [comment]
> Makes sense. That is a good use case.
> 
> What OS are you running on? I run `DOTENV_CONFIG_PATH=~/.env node -r dotenv/config my_script.js` on a mac machine and it finds the `.env` successfully.

I'm working on macOS as well. But a lit bit different is that I run it with WebStorm debugging mode instead of shell. 
image

**Comment by motdotla** [comment]
ok, that is a good use case. I will merge this soon-ish - probably sometime mid-next week if not sooner.

**Comment by brelian** [comment]
> ok, that is a good use case. I will merge this soon-ish - probably sometime mid-next week if not sooner.

That sounds great. Please let me know in case any changes.

**Comment by bdcarr** [comment]
Hello friends! Will this also work if I use it like this?

```javascript
// esm test script
process.env.DOTENV_CONFIG_PATH = `~/.env/brycesflorist.env`
import 'dotenv/config'

// cjs test script
require('dotenv').config({ path: `~/.env/brycesflorist.env` })
```

My use case is mocha test scripts that can be run in multiple test accounts. I use dotenv to pull the URL and access token from a local .env file, so people can pull the script from github and use their own test account to run it manually. Right now we use relative paths from `__dirname` but it's a bit of a hassle doing the `../../../` thing, so I'm stoked to see this PR.

**Comment by motdotla** [comment]
@bdcarr yes, this PR should solve that scenario for you as well.

**Comment by motdotla** [comment]
Released in 10.0.0 https://github.com/motdotla/dotenv/compare/v9.0.2...v10.0.0

**Pull request merged**
